#!/bin/bash
#source passphrase
source startuppassphrase
export coins="[{\"coin\":\"TXSCL000\",\"asset\":\"TXSCL000\",\"rpcport\":13273}]"
./stop7784
cd ..
./marketmaker "{\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins, \"rpcport\":7784}" &
