#!/bin/bash
#source passphrase
source startuppassphrase
export passphrase="startup$passphrase"
export coins="[{\"coin\":\"TXSCL\",\"asset\":\"TXSCL\",\"rpcport\":11821}]"
./stop

export mm="../bin/linux/marketmaker"

if [[ "$OSTYPE" == "darwin"* ]]; then
	mm="../bin/osx/marketmaker"
fi

$mm "{\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins, \"rpcport\":60000}" &